name: 'Setup Node.js and Dependencies'
description: 'Setup Node.js with pnpm and install dependencies'

runs:
  using: 'composite'
  steps:
    # pnpmをセットアップ
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: 10

    # Node.jsをセットアップ
    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: 22
        cache: pnpm

    # 依存パッケージをインストール
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
